
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Gestion compte Bancaire
//  @ File Name : ApplicationBancaire.java
//  @ Date : 26/03/2013
//  @ Author : Andy LECOQ
//
//




public class ApplicationBancaire {
	public static void main(String[] args) {
	
            
            Scanner clavier = new Scanner(System.in);
            boolean etatCompte=false;
            System.out.println("Nom du client :");
            String nomClient = clavier.nextLine();
            System.out.println("Numéro de compte du client :");
            int numeroCompteCourant = clavier.nextInt();
            System.out.println("Solde compte Courant du client :");
            float soldeCompteCourant = clavier.nextFloat();
            System.out.println("Numéro de compte epargne du client :");
            int numeroCompteEpargne = clavier.nextInt();
            System.out.println("Solde compte Epargne du client :");
            float soldeCompteEpargne = clavier.nextFloat();
            System.out.println("Interêt :");
            float tauxInteret = clavier.nextFloat();
            System.out.println("Ce compte est-il bloqué ?");
            String compteBloque=clavier.next();
           
            switch(compteBloque) 
            {
                case "y" :
                    etatCompte=true;break;
               case "n" :
                    etatCompte=false;break;
               default: 
                   System.out.println("Saisir N / Y");break;
            }
            Client client = new Client(nomClient, numeroCompteCourant, soldeCompteCourant, numeroCompteEpargne, soldeCompteEpargne, tauxInteret, etatCompte);
            client.consulterCompte();
            client.calculInterets();
            System.out.println("montant a crediter :");
            float montant = clavier.nextFloat();
            client.crediter(etatCompte, montant);
            
            System.out.println("montant a debiter :");
            montant = clavier.nextFloat();
            client.debiter(etatCompte, montant);
            System.out.println("Les intérêts du compte épargne de"+nomClient+" sont de"+client.calculInterets()+" euros");
            client.consulterCompte();
            
	}
}
