//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 26/03/2013
//  @ Author : 
//
//




public class Client {
	private String nomClient;
	private CompteCourant compteCourantClient;
	private CompteEpargne compteEpargneClient;
	public Client(String nomClient, int numeroCompteBancaireCourant, float soldeCourant, int numeroCompteBancaireEpargne, float soldeEpargne, float tauxInteretEpargne, boolean etatCompte) 
        {
            this.nomClient=nomClient;
            compteCourantClient= new CompteCourant(numeroCompteBancaireCourant, soldeCourant);
            compteEpargneClient= new CompteEpargne(numeroCompteBancaireEpargne, soldeEpargne, tauxInteretEpargne, etatCompte);
	}
	
	public void consulterCompte()
        {
            System.out.println("Compte de :"+getNomClient());
            System.out.println(compteCourantClient.toString());
            System.out.println(compteEpargneClient.toString());            
	}
	
	public String getNomClient()
        {
            return nomClient;
	}
	
	public void debiter(boolean choixCompte, float montantCredite) 
        {
            if(choixCompte==false)
            {
                compteEpargneClient.debiter(montantCredite);
            }
            else
            {
                compteCourantClient.debiter(montantCredite);
            }
	}
	
	public float calculInterets()
        {
        float calculeInterets= compteEpargneClient.getsolde()*(compteEpargneClient.getTauxInterets()/100);
	compteEpargneClient.ajouterInterets(calculeInterets);
        
        return calculeInterets;
	}
	
	public void crediter(boolean choixCompte, float montantCredite)
        {
            if(choixCompte==false)
            {
                compteCourantClient.crediter(montantCredite);
            }
            else
            {
                compteEpargneClient.crediter(montantCredite);
            }
	}
}
