//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CompteEpargne.java
//  @ Date : 26/03/2013
//  @ Author : 
//
//




public class CompteEpargne {
	private int numeroCompteBancaire;
	private float tauxInteret;
	private boolean compteBloque;
	private float solde;
	public CompteEpargne(int numeroCompteBancaire, float solde, float tauxInteret, boolean compteBloque)
        {
            this.numeroCompteBancaire=numeroCompteBancaire;
            this.tauxInteret=tauxInteret;
            this.solde=solde;
            this.compteBloque=compteBloque;
	}
	
	public String toString()
        {
            String informationCompte;
            informationCompte="compte non bloqué";
            if(compteBloque==true)
            {
                   informationCompte="compte bloqué";
            }
            
            
        return "Compte épargne numéro "+numeroCompteBancaire+", a "+tauxInteret+"% de taux d'intérêts, de solde = "+solde+" euros, "+informationCompte;
	
	}
	
	public void crediter(float montantCredite) 
        {
            solde=solde+montantCredite;
            System.out.println("On crédite "+montantCredite+" euros au compte "+numeroCompteBancaire);
	}
	
	public void debiter(float montantDebite) 
        {
            if(solde>=montantDebite && compteBloque==false)
            {
                solde=solde-montantDebite;
                System.out.println("On retire"+montantDebite+ "euros au compte "+numeroCompteBancaire);
            }
	}
	
	public void ajouterInterets(float interetsCalcules)
        {
            solde=solde+interetsCalcules;
	}
	
	public float getsolde() 
        {
            return solde;
	
	}
	
	public float getTauxInterets() 
        {
        return tauxInteret;
	}
}
