package distributeurboissonsv1;

//

import java.util.logging.Level;
import java.util.logging.Logger;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DistributeurDeBoissons.java
//  @ Date : 14/05/2013
//  @ Author : 
//
//




public class DistributeurDeBoissons {
	private float caisse;
	private float compteur;
	private int nombreGobelets;
	private float prixProduit;
	public DistributeurDeBoissons() 
        {
            caisse=10;
            compteur=0;
            nombreGobelets=50;
	}
	
	public DistributeurDeBoissons(float caisse, float compteur, int nombreGobelets)
        {
            this.caisse=caisse;
            this.compteur=compteur;
            this.nombreGobelets=nombreGobelets;
	}
	
	public void setPrixProduit(float prixProduit)
        {
            this.prixProduit=prixProduit;
	}
	
	public float monnaie()
        {
            float rendreMonnaie=0;
            rendreMonnaie=compteur-prixProduit;
           return rendreMonnaie;
	}
	
	public String etat()
        {
            return "Caisse : "+caisse+"\n Compteur : "+compteur ;
	
	}
	
	public boolean presenceGobelet() 
        {
         boolean presenceGobelet=true;
         if(nombreGobelets<=0)
            {
                presenceGobelet=false;
            }
         return presenceGobelet;	
	}
	
	public boolean ajouterArgent(float somme)
        {
            boolean sommePositive=true;
            if(somme>0)
            {
                compteur=compteur+somme;
            }
            else
            {
                sommePositive=false;
            }
            return sommePositive;
	
	}
	
	public float annuler()
        {
        float monnaieARendre;
        monnaieARendre=compteur;
        
        compteur=0;
         return monnaieARendre;
	
	}
	
	public Validation validerChoix() 
        {
           Validation validation= Validation.VALIDATION_OK;
          if(monnaie() < 0)
          {
              validation=Validation.ARGENT_INSUFISANT;
          }
          if(presenceGobelet()==false)
          {
              validation=Validation.PLUS_DE_GOBELET;
          }
        return validation;
	
	}
	
	public float preparerProduit() 
        {
            int tempsSec=5;
            tempsSec=tempsSec*1000;
            System.out.println("Boisson en préparation . . .");
            try
            {
                Thread.sleep(tempsSec);
            } catch (InterruptedException ex)
            {
                Logger.getLogger(DistributeurDeBoissons.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Boisson prête");
            System.out.println("Monnaie :"+monnaie());
            caisse=caisse+prixProduit;
            nombreGobelets--;
            compteur=0;
        return monnaie();
	
	}
}
