package distributeurboissonsv1;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Principale.java
//  @ Date : 14/05/2013
//  @ Author : 
//
//




public class Principale {

	public static void main(String[] args) {
         IHMDistributeur ihmDistributeur = new IHMDistributeur();
	 DistributeurDeBoissons distributeurDeBoissons = new DistributeurDeBoissons(10, 0, 10);

         ihmDistributeur.selectionnerChoix(distributeurDeBoissons);
	}
}

