//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Point.java
//  @ Date : 09/04/2013
//  @ Author : 
//
//



package tpwifibot;


public class Point {
	private short x;
	private short y;
	public Point(short x, short y) {
	
	}
	
	public Point() {
	
	}
	
	private void translateX(short dX) {
	
	}
	
	private void translateY(short dY) {
	
	}
	
	public short getX()
        {
            return x;
	}
	
	public short getY()
        {
            return y;
	}
	
	public void affiche() {
	
	}
}
