//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TestWifiBot.java
//  @ Date : 09/04/2013
//  @ Author : 
//
//



package tpwifibot;


public class TestWifiBot {
	private WifiBot WifiBot;
	public static void main(String args[]) {
	
	}
}
