//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TestPNB.java
//  @ Date : 12/03/2013
//  @ Author : 
//
//



package Exercice2;


public class TestPNB {
	public static void main(String[] args) {
            
            int année=2003; 
            float PNB=7250.0f;
            String nomPays="Seychelles";
            Pays p= new Pays(nomPays, 6700 , année);
          
            p.tauxCroissance(PNB);
            
            p.affiche();
        System.out.println("Pays "+nomPays+" : PNB de "+PNB+" $ pour l'année "+(année+1));
        System.out.println("Taux de croissance pour "+(année+1)+", avec PNB de "+PNB+" $ -> "+p.tauxCroissance(7250.0f));
	}
}
